/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import beans.AlunoV4;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import beans.MensalidadeV4;
import dao.AlunoV4DAO;
import dao.MensalidadeV4DAO;
import java.util.ArrayList;


/**
 *
 * @author pedro
 */
public class FormMensalidadeV4 extends javax.swing.JFrame {

    /**
     * Creates new form MensalidadeV4
     */
    public FormMensalidadeV4() {
        initComponents();
       this.setSize(500,480);
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_ALUNO = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txt_Valor = new javax.swing.JTextField();
        txt_DataVencimento = new javax.swing.JTextField();
        txt_DataPagamento = new javax.swing.JTextField();
        txt_DataEmissao = new javax.swing.JTextField();
        Label_Valor = new javax.swing.JLabel();
        Label_DataVencimento = new javax.swing.JLabel();
        Label_DataPagamento = new javax.swing.JLabel();
        Label_DataEmissao = new javax.swing.JLabel();
        Label_DataEmissao1 = new javax.swing.JLabel();
        ComboBox_Aluno = new javax.swing.JComboBox<>();
        btn_Atualizar = new javax.swing.JToggleButton();
        btn_Inserir = new javax.swing.JToggleButton();
        btn_Deletar = new javax.swing.JToggleButton();
        btn_Voltar = new javax.swing.JToggleButton();

        txt_ALUNO.setEditable(false);
        txt_ALUNO.setBackground(new java.awt.Color(230, 230, 230));
        txt_ALUNO.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        txt_ALUNO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ALUNO.setText("ALUNO");
        txt_ALUNO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_ALUNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ALUNOActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Mensalidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook", 1, 24))); // NOI18N

        txt_Valor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_Valor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Valor.setMinimumSize(new java.awt.Dimension(30, 40));
        txt_Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ValorActionPerformed(evt);
            }
        });

        txt_DataVencimento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_DataVencimento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_DataVencimento.setMinimumSize(new java.awt.Dimension(30, 40));
        txt_DataVencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DataVencimentoActionPerformed(evt);
            }
        });

        txt_DataPagamento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_DataPagamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_DataPagamento.setMinimumSize(new java.awt.Dimension(30, 40));
        txt_DataPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DataPagamentoActionPerformed(evt);
            }
        });

        txt_DataEmissao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_DataEmissao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_DataEmissao.setMinimumSize(new java.awt.Dimension(30, 40));
        txt_DataEmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DataEmissaoActionPerformed(evt);
            }
        });

        Label_Valor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Valor.setText("Valor:");
        Label_Valor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Label_DataVencimento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_DataVencimento.setText("Data de Vencimento:");
        Label_DataVencimento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Label_DataPagamento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_DataPagamento.setText("Data de Pagamento:");
        Label_DataPagamento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Label_DataEmissao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_DataEmissao.setText("Data de Emissão:");
        Label_DataEmissao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Label_DataEmissao1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_DataEmissao1.setText("Aluno:");
        Label_DataEmissao1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ComboBox_Aluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_Aluno.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ComboBox_AlunoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btn_Atualizar.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_Atualizar.setText("ATUALIZAR");
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });

        btn_Inserir.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_Inserir.setText("INSERIR");
        btn_Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InserirActionPerformed(evt);
            }
        });

        btn_Deletar.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_Deletar.setText("DELETAR");
        btn_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeletarActionPerformed(evt);
            }
        });

        btn_Voltar.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_Voltar.setText("< VOLTAR");
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Label_DataEmissao1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ComboBox_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Label_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Label_DataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_DataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Label_DataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_DataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Label_DataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_DataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_Inserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Deletar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Voltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_DataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_DataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_DataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label_DataEmissao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBox_Aluno, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ValorActionPerformed

    private void txt_DataVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DataVencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DataVencimentoActionPerformed

    private void txt_DataPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DataPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DataPagamentoActionPerformed

    private void txt_DataEmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DataEmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DataEmissaoActionPerformed

    private void txt_ALUNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ALUNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ALUNOActionPerformed

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        // TODO add your handling code here:
       String idMensalidadeStr = JOptionPane.showInputDialog(this, "Informe o ID da mensalidade a ser atualizada:");
if (idMensalidadeStr == null || idMensalidadeStr.isEmpty()) {
    return;  // Se o usuário cancelar ou não fornecer o ID, interromper a operação
}

try {
    int idMensalidade = Integer.parseInt(idMensalidadeStr);
    MensalidadeV4DAO dao = new MensalidadeV4DAO();
    MensalidadeV4 mensalidade = dao.buscarPorId(idMensalidade);

    if (mensalidade == null) {
        JOptionPane.showMessageDialog(this, "Mensalidade não encontrada");
        return;
    }

    // Solicitar novas informações
    String dataEmissao = JOptionPane.showInputDialog(this, "Data de Emissão:", mensalidade.getData_emissao());
    String dataVencimento = JOptionPane.showInputDialog(this, "Data de Vencimento:", mensalidade.getData_vencimento());
    String dataPagamento = JOptionPane.showInputDialog(this, "Data de Pagamento:", mensalidade.getData_pagamento());
    String valor = JOptionPane.showInputDialog(this, "Valor:", mensalidade.getValor());

    // Verifique se o ComboBox_Aluno está acessível e obtem o RA do aluno
    int raAlunoSelecionado = ComboBox_Aluno.getSelectedIndex() + 1;

    // Atualizar o objeto mensalidade com novas informações
    mensalidade.setData_emissao(dataEmissao);
    mensalidade.setData_vencimento(dataVencimento);
    mensalidade.setData_pagamento(dataPagamento);
    mensalidade.setValor(valor);
    mensalidade.setRA(raAlunoSelecionado); // Não esquecer de atualizar o RA

    // Atualizar no banco de dados
    dao.atualizar(mensalidade, raAlunoSelecionado);
    JOptionPane.showMessageDialog(this, "Mensalidade atualizada com sucesso!");

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "ID da mensalidade inválido");
} catch (SQLException ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Erro ao atualizar mensalidade.");
}
    }//GEN-LAST:event_btn_AtualizarActionPerformed

    private void btn_InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InserirActionPerformed
        // TODO add your handling code here:
        String Valor = txt_Valor.getText(); 
        String dataVencimento = txt_DataVencimento.getText();
        String dataEmissao = txt_DataEmissao.getText();
        String dataPagamento = txt_DataPagamento.getText();

         // Obtendo o ID do curso selecionado na Combo Box
         int raAlunoSelecionado = ComboBox_Aluno.getSelectedIndex() + 1;
        
        MensalidadeV4 mensalidade = new MensalidadeV4();
        mensalidade.setData_emissao(dataEmissao);
        mensalidade.setData_pagamento(dataPagamento);
        mensalidade.setData_vencimento(dataVencimento);
        mensalidade.setValor(Valor);

        try {
            MensalidadeV4DAO dao = new MensalidadeV4DAO();
            dao.inserir(mensalidade, raAlunoSelecionado);
            JOptionPane.showMessageDialog(this, "Mensalidade inserido com sucesso!");
        }catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao inserir Mensalidade.");
        }
    }//GEN-LAST:event_btn_InserirActionPerformed

    private void btn_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeletarActionPerformed
        // TODO add your handling code here:
        String idMensalidade = JOptionPane.showInputDialog(this, "Insira o id da mensalidade a ser deletado:");

        // Verifica se um valor foi inserido
        if (idMensalidade != null && !idMensalidade.trim().isEmpty()) {
            try {
                MensalidadeV4DAO dao = new MensalidadeV4DAO();
                int id_mensalidade = Integer.parseInt(idMensalidade.trim()); // Converte o RA para inteiro
                dao.deletar(id_mensalidade); // Assume que o método deletar no DAO aceita um RA como inteiro
                JOptionPane.showMessageDialog(this, "Mensalidade deletado com sucesso!");
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Mensalidade inválido. Insira um ID válido.");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao deletar mensalidade.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "ID não inserido.");
        }
    }//GEN-LAST:event_btn_DeletarActionPerformed

    private void ComboBox_AlunoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ComboBox_AlunoAncestorAdded
        // TODO add your handling code here:
           try {
    AlunoV4DAO dao = new AlunoV4DAO();
    ArrayList<AlunoV4> lista = dao.listarRA();
    
    ComboBox_Aluno.removeAllItems();
    
    for(AlunoV4 c : lista){
        ComboBox_Aluno.addItem(c.getNome_aluno());
    }
} catch (SQLException ex) {
    ex.printStackTrace(); // Print the stack trace to see the details of the exception
    // Handle the exception as per your application's requirements

    }      
        
    }//GEN-LAST:event_ComboBox_AlunoAncestorAdded

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        // TODO add your handling code here:
         FormEditor Editor = new FormEditor();
    Editor.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btn_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MensalidadeV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MensalidadeV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MensalidadeV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MensalidadeV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMensalidadeV4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_Aluno;
    private javax.swing.JLabel Label_DataEmissao;
    private javax.swing.JLabel Label_DataEmissao1;
    private javax.swing.JLabel Label_DataPagamento;
    private javax.swing.JLabel Label_DataVencimento;
    private javax.swing.JLabel Label_Valor;
    private javax.swing.JToggleButton btn_Atualizar;
    private javax.swing.JToggleButton btn_Deletar;
    private javax.swing.JToggleButton btn_Inserir;
    private javax.swing.JToggleButton btn_Voltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_ALUNO;
    private javax.swing.JTextField txt_DataEmissao;
    private javax.swing.JTextField txt_DataPagamento;
    private javax.swing.JTextField txt_DataVencimento;
    private javax.swing.JTextField txt_Valor;
    // End of variables declaration//GEN-END:variables
}
