/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

/**
 *
 * @author pedro
 */
public class FormRegistrar extends javax.swing.JFrame {

    /**
     * Creates new form FormRegistrar
     */
    public FormRegistrar() {
        initComponents();
        this.setSize(916, 600);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Aluno = new javax.swing.JToggleButton();
        btn_Menu = new javax.swing.JButton();
        btn_Professor = new javax.swing.JToggleButton();
        Label_Roxa = new javax.swing.JLabel();
        Label_Roxa2 = new javax.swing.JLabel();
        Label_Roxa3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_Aluno.setBackground(new java.awt.Color(102, 51, 255));
        btn_Aluno.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btn_Aluno.setForeground(new java.awt.Color(204, 204, 204));
        btn_Aluno.setText("Aluno");
        btn_Aluno.setBorder(null);
        btn_Aluno.setContentAreaFilled(false);
        btn_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlunoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Aluno);
        btn_Aluno.setBounds(70, 265, 187, 34);

        btn_Menu.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btn_Menu.setForeground(new java.awt.Color(204, 204, 204));
        btn_Menu.setText("Menu");
        btn_Menu.setBorder(null);
        btn_Menu.setContentAreaFilled(false);
        btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Menu);
        btn_Menu.setBounds(70, 373, 187, 34);

        btn_Professor.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        btn_Professor.setForeground(new java.awt.Color(204, 204, 204));
        btn_Professor.setText("Professor");
        btn_Professor.setBorder(null);
        btn_Professor.setContentAreaFilled(false);
        btn_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Professor);
        btn_Professor.setBounds(72, 319, 187, 34);

        Label_Roxa.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        Label_Roxa.setForeground(new java.awt.Color(140, 82, 255));
        Label_Roxa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Roxa.setText("Bem-vindo!");
        getContentPane().add(Label_Roxa);
        Label_Roxa.setBounds(10, 110, 320, 50);

        Label_Roxa2.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        Label_Roxa2.setForeground(new java.awt.Color(66, 135, 156));
        Label_Roxa2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Roxa2.setText("como:");
        getContentPane().add(Label_Roxa2);
        Label_Roxa2.setBounds(18, 200, 300, 50);

        Label_Roxa3.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        Label_Roxa3.setForeground(new java.awt.Color(66, 135, 156));
        Label_Roxa3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Roxa3.setText("Registrar-se");
        getContentPane().add(Label_Roxa3);
        Label_Roxa3.setBounds(10, 160, 320, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pedro\\Desktop\\DesignNovo\\Tela Registro.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1070, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlunoActionPerformed
        // TODO add your handling code here:
        FormAlunoV4 AlunoV4 = new FormAlunoV4();
        AlunoV4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_AlunoActionPerformed

    private void btn_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProfessorActionPerformed
        // TODO add your handling code here:
        FormProfessorV4 ProfessorV4 = new FormProfessorV4();
        ProfessorV4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ProfessorActionPerformed

    private void btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuActionPerformed
        // TODO add your handling code here:
        FormTelaMenu menu = new FormTelaMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Roxa;
    private javax.swing.JLabel Label_Roxa2;
    private javax.swing.JLabel Label_Roxa3;
    private javax.swing.JToggleButton btn_Aluno;
    private javax.swing.JButton btn_Menu;
    private javax.swing.JToggleButton btn_Professor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
