/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import beans.AlunoV4;
import beans.CursoV4;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import beans.MatriculaV4;
import dao.AlunoV4DAO;
import dao.CursoV4DAO;
import dao.MatriculaV4DAO;
import java.util.ArrayList;


/**
 *
 * @author pedro
 */
public class FormMatriculaV4 extends javax.swing.JFrame {

    /**
     * Creates new form FormsMatriculaV4
     */
    public FormMatriculaV4() {
        initComponents();
        this.setSize(587,450);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Frame = new javax.swing.JPanel();
        btn_Atualizar = new javax.swing.JToggleButton();
        btn_Inserir = new javax.swing.JToggleButton();
        txt_Data_Efetivação = new javax.swing.JTextField();
        txt_Data_Conclusão = new javax.swing.JTextField();
        Label_Efetivacao = new javax.swing.JLabel();
        Label_Conclusao = new javax.swing.JLabel();
        Label_Conclusao1 = new javax.swing.JLabel();
        Label_Conclusao2 = new javax.swing.JLabel();
        ComboBox_Curso = new javax.swing.JComboBox<>();
        ComboBox_Aluno = new javax.swing.JComboBox<>();
        btn_Voltar = new javax.swing.JToggleButton();
        btn_Deletar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main_Frame.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Matrícula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook", 1, 24))); // NOI18N

        btn_Atualizar.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_Atualizar.setText("ATUALIZAR");
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });

        btn_Inserir.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_Inserir.setText("INSERIR");
        btn_Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InserirActionPerformed(evt);
            }
        });

        txt_Data_Efetivação.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Data_Efetivação.setText("YY--MM--DD");
        txt_Data_Efetivação.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Data_Efetivação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Data_EfetivaçãoActionPerformed(evt);
            }
        });

        txt_Data_Conclusão.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Data_Conclusão.setText("YY--MM--DD");
        txt_Data_Conclusão.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Label_Efetivacao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Efetivacao.setText("Data de Efetivação:");
        Label_Efetivacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Label_Conclusao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Conclusao.setText("Data de Conlusão:");
        Label_Conclusao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Label_Conclusao1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Conclusao1.setText("Curso:");
        Label_Conclusao1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Label_Conclusao2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Conclusao2.setText("Aluno:");
        Label_Conclusao2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ComboBox_Curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_Curso.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ComboBox_CursoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ComboBox_Curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_CursoActionPerformed(evt);
            }
        });

        ComboBox_Aluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_Aluno.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ComboBox_AlunoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ComboBox_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_AlunoActionPerformed(evt);
            }
        });

        btn_Voltar.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_Voltar.setText("< VOLTAR");
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });

        btn_Deletar.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btn_Deletar.setText("DELETAR");
        btn_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Main_FrameLayout = new javax.swing.GroupLayout(Main_Frame);
        Main_Frame.setLayout(Main_FrameLayout);
        Main_FrameLayout.setHorizontalGroup(
            Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_FrameLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Main_FrameLayout.createSequentialGroup()
                        .addGroup(Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Conclusao2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Main_FrameLayout.createSequentialGroup()
                                .addComponent(Label_Conclusao, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Data_Conclusão, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Main_FrameLayout.createSequentialGroup()
                                .addComponent(btn_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(67, Short.MAX_VALUE))
                    .addGroup(Main_FrameLayout.createSequentialGroup()
                        .addGroup(Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ComboBox_Aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Main_FrameLayout.createSequentialGroup()
                                        .addComponent(Label_Conclusao1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ComboBox_Curso, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(Main_FrameLayout.createSequentialGroup()
                                    .addComponent(Label_Efetivacao, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_Data_Efetivação, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        Main_FrameLayout.setVerticalGroup(
            Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_FrameLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label_Conclusao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBox_Aluno, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Conclusao1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_Curso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Conclusao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Data_Conclusão, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Efetivacao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Data_Efetivação, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btn_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main_Frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main_Frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        // TODO add your handling code here:
        String idMatriculaStr = JOptionPane.showInputDialog(this, "Informe o ID da matrícula a ser atualizada:");
    if (idMatriculaStr == null || idMatriculaStr.isEmpty()) {
        return; // Se o usuário cancelar ou não fornecer o ID, interromper a operação
    }

    try {
        int idMatricula = Integer.parseInt(idMatriculaStr);
        MatriculaV4DAO dao = new MatriculaV4DAO();
        MatriculaV4 matricula = dao.buscarPorId(idMatricula);

        if (matricula == null) {
            JOptionPane.showMessageDialog(this, "Matrícula não encontrada.");
            return;
        }

        // Solicitar novas informações
        String dataEfetivacao = JOptionPane.showInputDialog(this, "Data de Efetivação:", matricula.getData_efetivacao());
        String dataTermino = JOptionPane.showInputDialog(this, "Data de Término:", matricula.getData_termino());
        
        // Obtendo o ID do curso selecionado na Combo Box
        int idCursoSelecionado = ComboBox_Curso.getSelectedIndex() + 1;
        int raAlunoSelecionado = ComboBox_Aluno.getSelectedIndex() + 1;

        // Atualizar o objeto matrícula com novas informações
        matricula.setData_efetivacao(dataEfetivacao);
        matricula.setData_termino(dataTermino);

        // Atualizar no banco de dados
        dao.atualizar(matricula, idCursoSelecionado, raAlunoSelecionado);
        JOptionPane.showMessageDialog(this, "Matrícula atualizada com sucesso!");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID da matrícula inválido.");
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao atualizar matrícula.");
        
    }
    }//GEN-LAST:event_btn_AtualizarActionPerformed

    private void btn_InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InserirActionPerformed
        // TODO add your handling code here:
        String dataEfetivacao = txt_Data_Efetivação.getText();
        String dataTermino = txt_Data_Conclusão.getText();
        
         // Obtendo o ID do curso selecionado na Combo Box
    int idCursoSelecionado = ComboBox_Curso.getSelectedIndex() + 1;
    int raAlunoSelecionado = ComboBox_Aluno.getSelectedIndex() + 1;

        MatriculaV4 matricula = new MatriculaV4();
        matricula.setData_efetivacao(dataEfetivacao);
        matricula.setData_termino(dataTermino);

        try {
            MatriculaV4DAO dao = new MatriculaV4DAO();
            dao.inserir(matricula, idCursoSelecionado, raAlunoSelecionado);
            JOptionPane.showMessageDialog(this, "Matrícula inserido com sucesso!");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao inserir matrícula.");
        }
    }//GEN-LAST:event_btn_InserirActionPerformed

    private void txt_Data_EfetivaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Data_EfetivaçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Data_EfetivaçãoActionPerformed

    private void ComboBox_CursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_CursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_CursoActionPerformed

    private void ComboBox_CursoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ComboBox_CursoAncestorAdded
        // TODO add your handling code here:
        try {
    CursoV4DAO dao = new CursoV4DAO();
    ArrayList<CursoV4> lista = dao.listarCursos();
    
    ComboBox_Curso.removeAllItems();
    
    for(CursoV4 c : lista){
        ComboBox_Curso.addItem(c.getNome_curso());
    }
} catch (SQLException ex) {
    ex.printStackTrace(); // Print the stack trace to see the details of the exception
    // Handle the exception as per your application's requirements
}
    }//GEN-LAST:event_ComboBox_CursoAncestorAdded

    private void ComboBox_AlunoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ComboBox_AlunoAncestorAdded
        // TODO add your handling code here:
        try {
    AlunoV4DAO dao = new AlunoV4DAO();
    ArrayList<AlunoV4> lista = dao.listarRA();
    
    ComboBox_Aluno.removeAllItems();
    
    for(AlunoV4 c : lista){
        ComboBox_Aluno.addItem(c.getNome_aluno());
    }
} catch (SQLException ex) {
    ex.printStackTrace(); // Print the stack trace to see the details of the exception
    // Handle the exception as per your application's requirements
}
    }//GEN-LAST:event_ComboBox_AlunoAncestorAdded

    private void ComboBox_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_AlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_AlunoActionPerformed

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        // TODO add your handling code here:
         FormEditor editar = new FormEditor();
    editar.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btn_VoltarActionPerformed

    private void btn_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeletarActionPerformed
        // TODO add your handling code here:
         String idMatricula = JOptionPane.showInputDialog(this, "Insira o id da matrícula a ser deletado:");

    // Verifica se um valor foi inserido
    if (idMatricula != null && !idMatricula.trim().isEmpty()) {
        try {
            MatriculaV4DAO dao = new MatriculaV4DAO();
            int IDMatricula = Integer.parseInt(idMatricula.trim()); // Converte o id para inteiro
            dao.deletar(IDMatricula); // Assume que o método deletar no DAO aceita um id como inteiro
            JOptionPane.showMessageDialog(this, "Matrícula deletado com sucesso!");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "id inválido. Insira um número válido.");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao deletar matrícula.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "id não inserido.");
    }
    }//GEN-LAST:event_btn_DeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMatriculaV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMatriculaV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMatriculaV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMatriculaV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMatriculaV4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_Aluno;
    private javax.swing.JComboBox<String> ComboBox_Curso;
    private javax.swing.JLabel Label_Conclusao;
    private javax.swing.JLabel Label_Conclusao1;
    private javax.swing.JLabel Label_Conclusao2;
    private javax.swing.JLabel Label_Efetivacao;
    private javax.swing.JPanel Main_Frame;
    private javax.swing.JToggleButton btn_Atualizar;
    private javax.swing.JToggleButton btn_Deletar;
    private javax.swing.JToggleButton btn_Inserir;
    private javax.swing.JToggleButton btn_Voltar;
    private javax.swing.JTextField txt_Data_Conclusão;
    private javax.swing.JTextField txt_Data_Efetivação;
    // End of variables declaration//GEN-END:variables
}
