/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import beans.AlunoV4;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import beans.MensalidadeV4;
import dao.AlunoV4DAO;
import dao.MensalidadeV4DAO;
import java.util.ArrayList;

/**
 *
 * @author pedro
 */
public class FormMensalidadeV4 extends javax.swing.JFrame {

    /**
     * Creates new form MensalidadeV4
     */
    public FormMensalidadeV4() {
        initComponents();
       this.setSize(960, 600);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_ALUNO = new javax.swing.JTextField();
        Label_Valor = new javax.swing.JLabel();
        txt_Valor = new javax.swing.JTextField();
        txt_DataVencimento = new javax.swing.JTextField();
        Label_DataVencimento = new javax.swing.JLabel();
        Label_DataPagamento = new javax.swing.JLabel();
        txt_DataPagamento = new javax.swing.JTextField();
        Label_DataEmissao = new javax.swing.JLabel();
        txt_DataEmissao = new javax.swing.JTextField();
        Label_DataEmissao1 = new javax.swing.JLabel();
        ComboBox_Aluno = new javax.swing.JComboBox<>();
        btn_Atualizar = new javax.swing.JToggleButton();
        btn_Deletar = new javax.swing.JToggleButton();
        btn_Inserir = new javax.swing.JToggleButton();
        btn_Voltar = new javax.swing.JToggleButton();
        Label_DataEmissao2 = new javax.swing.JLabel();
        Label_DataVencimento1 = new javax.swing.JLabel();
        Label_DataPagamento1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        txt_ALUNO.setEditable(false);
        txt_ALUNO.setBackground(new java.awt.Color(230, 230, 230));
        txt_ALUNO.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        txt_ALUNO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ALUNO.setText("ALUNO");
        txt_ALUNO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_ALUNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ALUNOActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Label_Valor.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_Valor.setForeground(new java.awt.Color(204, 204, 204));
        Label_Valor.setText("Valor:");
        getContentPane().add(Label_Valor);
        Label_Valor.setBounds(50, 65, 50, 40);

        txt_Valor.setBackground(new java.awt.Color(3, 16, 50));
        txt_Valor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_Valor.setForeground(new java.awt.Color(204, 204, 204));
        txt_Valor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Valor.setMinimumSize(new java.awt.Dimension(30, 40));
        txt_Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ValorActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Valor);
        txt_Valor.setBounds(170, 90, 160, 34);

        txt_DataVencimento.setBackground(new java.awt.Color(3, 16, 50));
        txt_DataVencimento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_DataVencimento.setForeground(new java.awt.Color(204, 204, 204));
        txt_DataVencimento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_DataVencimento.setMinimumSize(new java.awt.Dimension(30, 40));
        txt_DataVencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DataVencimentoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_DataVencimento);
        txt_DataVencimento.setBounds(170, 164, 160, 34);

        Label_DataVencimento.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_DataVencimento.setForeground(new java.awt.Color(204, 204, 204));
        Label_DataVencimento.setText("Vencimento:");
        getContentPane().add(Label_DataVencimento);
        Label_DataVencimento.setBounds(50, 157, 100, 20);

        Label_DataPagamento.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_DataPagamento.setForeground(new java.awt.Color(204, 204, 204));
        Label_DataPagamento.setText("Pagamento:");
        getContentPane().add(Label_DataPagamento);
        Label_DataPagamento.setBounds(50, 230, 100, 20);

        txt_DataPagamento.setBackground(new java.awt.Color(3, 16, 50));
        txt_DataPagamento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_DataPagamento.setForeground(new java.awt.Color(204, 204, 204));
        txt_DataPagamento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_DataPagamento.setMinimumSize(new java.awt.Dimension(30, 40));
        txt_DataPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DataPagamentoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_DataPagamento);
        txt_DataPagamento.setBounds(170, 238, 160, 34);

        Label_DataEmissao.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_DataEmissao.setForeground(new java.awt.Color(204, 204, 204));
        Label_DataEmissao.setText(" Emissão:");
        getContentPane().add(Label_DataEmissao);
        Label_DataEmissao.setBounds(45, 300, 80, 20);

        txt_DataEmissao.setBackground(new java.awt.Color(3, 16, 50));
        txt_DataEmissao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_DataEmissao.setForeground(new java.awt.Color(204, 204, 204));
        txt_DataEmissao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_DataEmissao.setMinimumSize(new java.awt.Dimension(30, 40));
        txt_DataEmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DataEmissaoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_DataEmissao);
        txt_DataEmissao.setBounds(170, 310, 160, 34);

        Label_DataEmissao1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_DataEmissao1.setForeground(new java.awt.Color(204, 204, 204));
        Label_DataEmissao1.setText("Aluno:");
        getContentPane().add(Label_DataEmissao1);
        Label_DataEmissao1.setBounds(50, 363, 50, 40);

        ComboBox_Aluno.setBackground(new java.awt.Color(3, 16, 50));
        ComboBox_Aluno.setForeground(new java.awt.Color(204, 204, 204));
        ComboBox_Aluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_Aluno.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ComboBox_AlunoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(ComboBox_Aluno);
        ComboBox_Aluno.setBounds(170, 384, 160, 34);

        btn_Atualizar.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_Atualizar.setForeground(new java.awt.Color(204, 204, 204));
        btn_Atualizar.setText("ATUALIZAR");
        btn_Atualizar.setBorder(null);
        btn_Atualizar.setContentAreaFilled(false);
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Atualizar);
        btn_Atualizar.setBounds(30, 455, 154, 30);

        btn_Deletar.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_Deletar.setForeground(new java.awt.Color(204, 204, 204));
        btn_Deletar.setText("DELETAR");
        btn_Deletar.setBorder(null);
        btn_Deletar.setContentAreaFilled(false);
        btn_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Deletar);
        btn_Deletar.setBounds(30, 510, 154, 35);

        btn_Inserir.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_Inserir.setForeground(new java.awt.Color(204, 204, 204));
        btn_Inserir.setText("INSERIR");
        btn_Inserir.setBorder(null);
        btn_Inserir.setContentAreaFilled(false);
        btn_Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InserirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Inserir);
        btn_Inserir.setBounds(210, 453, 160, 33);

        btn_Voltar.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_Voltar.setForeground(new java.awt.Color(204, 204, 204));
        btn_Voltar.setText("< VOLTAR");
        btn_Voltar.setBorder(null);
        btn_Voltar.setContentAreaFilled(false);
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Voltar);
        btn_Voltar.setBounds(210, 512, 160, 33);

        Label_DataEmissao2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_DataEmissao2.setForeground(new java.awt.Color(204, 204, 204));
        Label_DataEmissao2.setText("Data de");
        getContentPane().add(Label_DataEmissao2);
        Label_DataEmissao2.setBounds(50, 284, 70, 20);

        Label_DataVencimento1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_DataVencimento1.setForeground(new java.awt.Color(204, 204, 204));
        Label_DataVencimento1.setText("Data de");
        getContentPane().add(Label_DataVencimento1);
        Label_DataVencimento1.setBounds(50, 140, 70, 20);

        Label_DataPagamento1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_DataPagamento1.setForeground(new java.awt.Color(204, 204, 204));
        Label_DataPagamento1.setText("Data de ");
        getContentPane().add(Label_DataPagamento1);
        Label_DataPagamento1.setBounds(50, 215, 70, 19);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pedro\\Desktop\\DesignNovo\\MensalidadeDark.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ValorActionPerformed

    private void txt_DataVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DataVencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DataVencimentoActionPerformed

    private void txt_DataPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DataPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DataPagamentoActionPerformed

    private void txt_DataEmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DataEmissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DataEmissaoActionPerformed

    private void txt_ALUNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ALUNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ALUNOActionPerformed

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        // TODO add your handling code here:
        String idMensalidadeStr = JOptionPane.showInputDialog(this, "Informe o ID da mensalidade a ser atualizada:");
        if (idMensalidadeStr == null || idMensalidadeStr.isEmpty()) {
            return;  // Se o usuário cancelar ou não fornecer o ID, interromper a operação
        }

        try {
            int idMensalidade = Integer.parseInt(idMensalidadeStr);
            MensalidadeV4DAO dao = new MensalidadeV4DAO();
            MensalidadeV4 mensalidade = dao.buscarPorId(idMensalidade);

            if (mensalidade == null) {
                JOptionPane.showMessageDialog(this, "Mensalidade não encontrada");
                return;
            }

            // Solicitar novas informações
            String dataEmissao = JOptionPane.showInputDialog(this, "Data de Emissão:", mensalidade.getData_emissao());
            String dataVencimento = JOptionPane.showInputDialog(this, "Data de Vencimento:", mensalidade.getData_vencimento());
            String dataPagamento = JOptionPane.showInputDialog(this, "Data de Pagamento:", mensalidade.getData_pagamento());
            String valor = JOptionPane.showInputDialog(this, "Valor:", mensalidade.getValor());

            // Verifique se o ComboBox_Aluno está acessível e obtem o RA do aluno
            int raAlunoSelecionado = ComboBox_Aluno.getSelectedIndex() + 1;

            // Atualizar o objeto mensalidade com novas informações
            mensalidade.setData_emissao(dataEmissao);
            mensalidade.setData_vencimento(dataVencimento);
            mensalidade.setData_pagamento(dataPagamento);
            mensalidade.setValor(valor);
            mensalidade.setRA(raAlunoSelecionado); // Não esquecer de atualizar o RA

            // Atualizar no banco de dados
            dao.atualizar(mensalidade, raAlunoSelecionado);
            JOptionPane.showMessageDialog(this, "Mensalidade atualizada com sucesso!");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID da mensalidade inválido");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao atualizar mensalidade.");
        }
    }//GEN-LAST:event_btn_AtualizarActionPerformed

    private void btn_InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InserirActionPerformed
        // TODO add your handling code here:
        String Valor = txt_Valor.getText();
        String dataVencimento = txt_DataVencimento.getText();
        String dataEmissao = txt_DataEmissao.getText();
        String dataPagamento = txt_DataPagamento.getText();

        // Obtendo o ID do curso selecionado na Combo Box
        int raAlunoSelecionado = ComboBox_Aluno.getSelectedIndex() + 1;

        MensalidadeV4 mensalidade = new MensalidadeV4();
        mensalidade.setData_emissao(dataEmissao);
        mensalidade.setData_pagamento(dataPagamento);
        mensalidade.setData_vencimento(dataVencimento);
        mensalidade.setValor(Valor);

        try {
            MensalidadeV4DAO dao = new MensalidadeV4DAO();
            dao.inserir(mensalidade, raAlunoSelecionado);
            JOptionPane.showMessageDialog(this, "Mensalidade inserido com sucesso!");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao inserir Mensalidade.");
        }
    }//GEN-LAST:event_btn_InserirActionPerformed

    private void btn_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeletarActionPerformed
        // TODO add your handling code here:
        String idMensalidade = JOptionPane.showInputDialog(this, "Insira o id da mensalidade a ser deletado:");

        // Verifica se um valor foi inserido
        if (idMensalidade != null && !idMensalidade.trim().isEmpty()) {
            try {
                MensalidadeV4DAO dao = new MensalidadeV4DAO();
                int id_mensalidade = Integer.parseInt(idMensalidade.trim()); // Converte o RA para inteiro
                dao.deletar(id_mensalidade); // Assume que o método deletar no DAO aceita um RA como inteiro
                JOptionPane.showMessageDialog(this, "Mensalidade deletado com sucesso!");
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Mensalidade inválido. Insira um ID válido.");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao deletar mensalidade.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "ID não inserido.");
        }
    }//GEN-LAST:event_btn_DeletarActionPerformed

    private void ComboBox_AlunoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ComboBox_AlunoAncestorAdded
        // TODO add your handling code here:
        try {
            AlunoV4DAO dao = new AlunoV4DAO();
            ArrayList<AlunoV4> lista = dao.listarRA();

            ComboBox_Aluno.removeAllItems();

            for (AlunoV4 c : lista) {
                ComboBox_Aluno.addItem(c.getNome_aluno());
            }
        } catch (SQLException ex) {
            ex.printStackTrace(); // Print the stack trace to see the details of the exception
            // Handle the exception as per your application's requirements

        }

    }//GEN-LAST:event_ComboBox_AlunoAncestorAdded

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        // TODO add your handling code here:
        FormEditor Editor = new FormEditor();
        Editor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MensalidadeV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MensalidadeV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MensalidadeV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MensalidadeV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMensalidadeV4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_Aluno;
    private javax.swing.JLabel Label_DataEmissao;
    private javax.swing.JLabel Label_DataEmissao1;
    private javax.swing.JLabel Label_DataEmissao2;
    private javax.swing.JLabel Label_DataPagamento;
    private javax.swing.JLabel Label_DataPagamento1;
    private javax.swing.JLabel Label_DataVencimento;
    private javax.swing.JLabel Label_DataVencimento1;
    private javax.swing.JLabel Label_Valor;
    private javax.swing.JToggleButton btn_Atualizar;
    private javax.swing.JToggleButton btn_Deletar;
    private javax.swing.JToggleButton btn_Inserir;
    private javax.swing.JToggleButton btn_Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_ALUNO;
    private javax.swing.JTextField txt_DataEmissao;
    private javax.swing.JTextField txt_DataPagamento;
    private javax.swing.JTextField txt_DataVencimento;
    private javax.swing.JTextField txt_Valor;
    // End of variables declaration//GEN-END:variables
}
