/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import beans.AlunoV4;
import dao.AlunoV4DAO;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author pedro
 */
public class FormChecarAluno extends javax.swing.JFrame {

    /**
     * 3333 Creates new form FormChecarAluno
     */
    public FormChecarAluno() {
        initComponents();
        this.setTitle("Visualizar");
         this.setSize(960, 638);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Menu = new javax.swing.JButton();
        btn_Notas = new javax.swing.JButton();
        btn_presenca = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_Menu.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btn_Menu.setForeground(new java.awt.Color(204, 204, 204));
        btn_Menu.setText("Menu");
        btn_Menu.setBorder(null);
        btn_Menu.setContentAreaFilled(false);
        btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Menu);
        btn_Menu.setBounds(93, 387, 210, 35);

        btn_Notas.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btn_Notas.setForeground(new java.awt.Color(204, 204, 204));
        btn_Notas.setText("Notas");
        btn_Notas.setBorder(null);
        btn_Notas.setContentAreaFilled(false);
        btn_Notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NotasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Notas);
        btn_Notas.setBounds(93, 315, 210, 35);

        btn_presenca.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btn_presenca.setForeground(new java.awt.Color(204, 204, 204));
        btn_presenca.setText("Presença");
        btn_presenca.setBorder(null);
        btn_presenca.setContentAreaFilled(false);
        btn_presenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_presencaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_presenca);
        btn_presenca.setBounds(93, 242, 210, 35);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(23, 27, 80));
        jTextField2.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(140, 82, 255));
        jTextField2.setText("Bem-vindo Aluno");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(40, 140, 330, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pedro\\Desktop\\DesignNovo\\Visualizar.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 950, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NotasActionPerformed
        // TODO add your handling code here:
        FormNotas Notas = new FormNotas();
        Notas.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_NotasActionPerformed

    private void btn_presencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_presencaActionPerformed
        // TODO add your handling code here:
        FormPresenca presenca = new FormPresenca();
        presenca.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_presencaActionPerformed

    private void btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuActionPerformed
        // TODO add your handling code here:
        FormTelaMenu menu = new FormTelaMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_MenuActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormChecarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormChecarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormChecarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormChecarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormChecarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Menu;
    private javax.swing.JButton btn_Notas;
    private javax.swing.JButton btn_presenca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
