/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import beans.AlunoV4;
import dao.AlunoV4DAO;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class FormAtribuirAlunos extends javax.swing.JFrame {

    /**
     * Creates new form FormAtribuirAlunos
     */
    public FormAtribuirAlunos() {
        initComponents();

        this.setSize(500, 525);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_Presenca = new javax.swing.JLabel();
        Label_Notas = new javax.swing.JLabel();
        ComboBox_RA = new javax.swing.JComboBox<>();
        Label_RA = new javax.swing.JLabel();
        txt_NotaA1 = new javax.swing.JTextField();
        Label_Notas1 = new javax.swing.JLabel();
        Label_Notas2 = new javax.swing.JLabel();
        txt_Presenca = new javax.swing.JTextField();
        txt_NotaA3 = new javax.swing.JTextField();
        txt_NotaA2 = new javax.swing.JTextField();
        btn_menu = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "ALUNO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook", 1, 18))); // NOI18N

        Label_Presenca.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Label_Presenca.setText("Presença:");
        Label_Presenca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Label_Notas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Label_Notas.setText("Nota A2:");
        Label_Notas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ComboBox_RA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_RA.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ComboBox_RAAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ComboBox_RA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_RAActionPerformed(evt);
            }
        });

        Label_RA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Label_RA.setText("RA:");
        Label_RA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txt_NotaA1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        txt_NotaA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NotaA1ActionPerformed(evt);
            }
        });

        Label_Notas1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Label_Notas1.setText("Nota A3:");
        Label_Notas1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Label_Notas2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Label_Notas2.setText("Nota A1:");
        Label_Notas2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txt_Presenca.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        txt_Presenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PresencaActionPerformed(evt);
            }
        });

        txt_NotaA3.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        txt_NotaA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NotaA3ActionPerformed(evt);
            }
        });

        txt_NotaA2.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        txt_NotaA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NotaA2ActionPerformed(evt);
            }
        });

        btn_menu.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_menu.setText("Menu");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        btn_Salvar.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label_RA, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(Label_Notas2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(Label_Notas, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(Label_Notas1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(Label_Presenca, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(btn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_NotaA1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_RA, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NotaA2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NotaA3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Presenca, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_RA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_RA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Notas2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NotaA1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Notas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NotaA2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Notas1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NotaA3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Presenca, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Presenca, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBox_RAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_RAActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_ComboBox_RAActionPerformed

    private void ComboBox_RAAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ComboBox_RAAncestorAdded
        // TODO add your handling code here:
        try {
            AlunoV4DAO dao = new AlunoV4DAO();
            ArrayList<AlunoV4> lista = dao.listarRA();

            ComboBox_RA.removeAllItems();

            for (AlunoV4 c : lista) {
                String displayText = c.getRA() + " - " + c.getNome_aluno();
                ComboBox_RA.addItem(displayText);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_ComboBox_RAAncestorAdded

    private void txt_NotaA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NotaA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NotaA1ActionPerformed

    private void txt_PresencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PresencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PresencaActionPerformed

    private void txt_NotaA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NotaA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NotaA3ActionPerformed

    private void txt_NotaA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NotaA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NotaA2ActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:

        FormTelaMenu menu = new FormTelaMenu();
        menu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        // TODO add your handling code here:
        String notaA1 = txt_NotaA1.getText();
        String notaA2 = txt_NotaA2.getText();
        String notaA3 = txt_NotaA3.getText();
        String presenca = txt_Presenca.getText();

        // Obtendo o RA do aluno selecionado na Combo Box
        String selectedRA = (String) ComboBox_RA.getSelectedItem();
        int RA = Integer.parseInt(selectedRA.split(" - ")[0]); // Assumindo que o formato é "RA - Nome"

        AlunoV4 aluno = new AlunoV4();
        aluno.setRA(RA);
        aluno.setNota_A1(notaA1);
        aluno.setNota_A2(notaA2);
        aluno.setNota_A3(notaA3);
        aluno.setPresenca(presenca);

        try {
            AlunoV4DAO dao = new AlunoV4DAO();
            dao.atribuirNotas(aluno);
            JOptionPane.showMessageDialog(this, "Dados inseridos com sucesso!");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao inserir Dados.");
        }
    }//GEN-LAST:event_btn_SalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAtribuirAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAtribuirAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAtribuirAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAtribuirAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAtribuirAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_RA;
    private javax.swing.JLabel Label_Notas;
    private javax.swing.JLabel Label_Notas1;
    private javax.swing.JLabel Label_Notas2;
    private javax.swing.JLabel Label_Presenca;
    private javax.swing.JLabel Label_RA;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JButton btn_menu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_NotaA1;
    private javax.swing.JTextField txt_NotaA2;
    private javax.swing.JTextField txt_NotaA3;
    private javax.swing.JTextField txt_Presenca;
    // End of variables declaration//GEN-END:variables
}
