/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import beans.AlunoV4;
import beans.CursoV4;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import beans.MatriculaV4;
import dao.AlunoV4DAO;
import dao.CursoV4DAO;
import dao.MatriculaV4DAO;
import java.util.ArrayList;

/**
 *
 * @author pedro
 */
public class FormMatriculaV4 extends javax.swing.JFrame {

    /**
     * Creates new form FormsMatriculaV4
     */
    public FormMatriculaV4() {
        initComponents();
       this.setSize(960, 600);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Deletar = new javax.swing.JToggleButton();
        btn_Inserir = new javax.swing.JToggleButton();
        btn_Atualizar = new javax.swing.JToggleButton();
        btn_Voltar = new javax.swing.JToggleButton();
        ComboBox_Aluno = new javax.swing.JComboBox<>();
        Label_Conclusao2 = new javax.swing.JLabel();
        ComboBox_Curso = new javax.swing.JComboBox<>();
        Label_Conclusao1 = new javax.swing.JLabel();
        txt_Data_Conclusão = new javax.swing.JTextField();
        Label_Conclusao = new javax.swing.JLabel();
        txt_Data_Efetivação = new javax.swing.JTextField();
        Label_Efetivacao = new javax.swing.JLabel();
        Label_Conclusao3 = new javax.swing.JLabel();
        Label_Efetivacao1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_Deletar.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_Deletar.setForeground(new java.awt.Color(204, 204, 204));
        btn_Deletar.setText("DELETAR");
        btn_Deletar.setBorder(null);
        btn_Deletar.setContentAreaFilled(false);
        btn_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Deletar);
        btn_Deletar.setBounds(210, 480, 160, 32);

        btn_Inserir.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_Inserir.setForeground(new java.awt.Color(204, 204, 204));
        btn_Inserir.setText("INSERIR");
        btn_Inserir.setBorder(null);
        btn_Inserir.setContentAreaFilled(false);
        btn_Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InserirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Inserir);
        btn_Inserir.setBounds(30, 480, 150, 32);

        btn_Atualizar.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_Atualizar.setForeground(new java.awt.Color(204, 204, 204));
        btn_Atualizar.setText("ATUALIZAR");
        btn_Atualizar.setBorder(null);
        btn_Atualizar.setContentAreaFilled(false);
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Atualizar);
        btn_Atualizar.setBounds(34, 422, 140, 32);

        btn_Voltar.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_Voltar.setForeground(new java.awt.Color(204, 204, 204));
        btn_Voltar.setText("< VOLTAR");
        btn_Voltar.setBorder(null);
        btn_Voltar.setContentAreaFilled(false);
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Voltar);
        btn_Voltar.setBounds(210, 422, 160, 32);

        ComboBox_Aluno.setBackground(new java.awt.Color(3, 16, 50));
        ComboBox_Aluno.setForeground(new java.awt.Color(204, 204, 204));
        ComboBox_Aluno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_Aluno.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ComboBox_AlunoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ComboBox_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_AlunoActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox_Aluno);
        ComboBox_Aluno.setBounds(170, 140, 160, 35);

        Label_Conclusao2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_Conclusao2.setForeground(new java.awt.Color(204, 204, 204));
        Label_Conclusao2.setText("Aluno:");
        getContentPane().add(Label_Conclusao2);
        Label_Conclusao2.setBounds(50, 125, 50, 20);

        ComboBox_Curso.setBackground(new java.awt.Color(3, 16, 50));
        ComboBox_Curso.setForeground(new java.awt.Color(204, 204, 204));
        ComboBox_Curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_Curso.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ComboBox_CursoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ComboBox_Curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_CursoActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBox_Curso);
        ComboBox_Curso.setBounds(170, 213, 160, 35);

        Label_Conclusao1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_Conclusao1.setForeground(new java.awt.Color(204, 204, 204));
        Label_Conclusao1.setText("Curso:");
        getContentPane().add(Label_Conclusao1);
        Label_Conclusao1.setBounds(50, 193, 60, 30);

        txt_Data_Conclusão.setBackground(new java.awt.Color(3, 16, 50));
        txt_Data_Conclusão.setForeground(new java.awt.Color(204, 204, 204));
        txt_Data_Conclusão.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Data_Conclusão.setText("YY--MM--DD");
        txt_Data_Conclusão.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txt_Data_Conclusão);
        txt_Data_Conclusão.setBounds(170, 292, 160, 35);

        Label_Conclusao.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_Conclusao.setForeground(new java.awt.Color(204, 204, 204));
        Label_Conclusao.setText("Conlusão:");
        getContentPane().add(Label_Conclusao);
        Label_Conclusao.setBounds(50, 280, 80, 30);

        txt_Data_Efetivação.setEditable(false);
        txt_Data_Efetivação.setBackground(new java.awt.Color(3, 16, 50));
        txt_Data_Efetivação.setForeground(new java.awt.Color(204, 204, 204));
        txt_Data_Efetivação.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Data_Efetivação.setText("YY--MM--DD");
        txt_Data_Efetivação.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Data_Efetivação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Data_EfetivaçãoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Data_Efetivação);
        txt_Data_Efetivação.setBounds(170, 365, 160, 35);

        Label_Efetivacao.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_Efetivacao.setForeground(new java.awt.Color(204, 204, 204));
        Label_Efetivacao.setText("Efetivação:");
        getContentPane().add(Label_Efetivacao);
        Label_Efetivacao.setBounds(50, 352, 100, 30);

        Label_Conclusao3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_Conclusao3.setForeground(new java.awt.Color(204, 204, 204));
        Label_Conclusao3.setText("Data de ");
        getContentPane().add(Label_Conclusao3);
        Label_Conclusao3.setBounds(50, 267, 70, 20);

        Label_Efetivacao1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_Efetivacao1.setForeground(new java.awt.Color(204, 204, 204));
        Label_Efetivacao1.setText("Data de ");
        getContentPane().add(Label_Efetivacao1);
        Label_Efetivacao1.setBounds(50, 335, 70, 30);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(23, 27, 80));
        jTextField1.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(140, 82, 255));
        jTextField1.setText("Matrícula");
        jTextField1.setToolTipText("");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(110, 50, 190, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pedro\\Desktop\\DesignNovo\\MatriculaDark.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        // TODO add your handling code here:
        String idMatriculaStr = JOptionPane.showInputDialog(this, "Informe o ID da matrícula a ser atualizada:");
        if (idMatriculaStr == null || idMatriculaStr.isEmpty()) {
            return; // Se o usuário cancelar ou não fornecer o ID, interromper a operação
        }

        try {
            int idMatricula = Integer.parseInt(idMatriculaStr);
            MatriculaV4DAO dao = new MatriculaV4DAO();
            MatriculaV4 matricula = dao.buscarPorId(idMatricula);

            if (matricula == null) {
                JOptionPane.showMessageDialog(this, "Matrícula não encontrada.");
                return;
            }

            // Solicitar novas informações
            String dataEfetivacao = JOptionPane.showInputDialog(this, "Data de Efetivação:", matricula.getData_efetivacao());
            String dataTermino = JOptionPane.showInputDialog(this, "Data de Término:", matricula.getData_termino());

            // Obtendo o ID do curso selecionado na Combo Box
            int idCursoSelecionado = ComboBox_Curso.getSelectedIndex() + 1;
            int raAlunoSelecionado = ComboBox_Aluno.getSelectedIndex() + 1;

            // Atualizar o objeto matrícula com novas informações
            matricula.setData_efetivacao(dataEfetivacao);
            matricula.setData_termino(dataTermino);

            // Atualizar no banco de dados
            dao.atualizar(matricula, idCursoSelecionado, raAlunoSelecionado);
            JOptionPane.showMessageDialog(this, "Matrícula atualizada com sucesso!");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID da matrícula inválido.");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao atualizar matrícula.");

        }
    }//GEN-LAST:event_btn_AtualizarActionPerformed

    private void btn_InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InserirActionPerformed
        // TODO add your handling code here:
        String dataEfetivacao = txt_Data_Efetivação.getText();
        String dataTermino = txt_Data_Conclusão.getText();

        // Obtendo o ID do curso selecionado na Combo Box
        int idCursoSelecionado = ComboBox_Curso.getSelectedIndex() + 1;
        int raAlunoSelecionado = ComboBox_Aluno.getSelectedIndex() + 1;

        MatriculaV4 matricula = new MatriculaV4();
        matricula.setData_efetivacao(dataEfetivacao);
        matricula.setData_termino(dataTermino);

        try {
            MatriculaV4DAO dao = new MatriculaV4DAO();
            dao.inserir(matricula, idCursoSelecionado, raAlunoSelecionado);
            JOptionPane.showMessageDialog(this, "Matrícula inserido com sucesso!");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao inserir matrícula.");
        }
    }//GEN-LAST:event_btn_InserirActionPerformed

    private void txt_Data_EfetivaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Data_EfetivaçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Data_EfetivaçãoActionPerformed

    private void ComboBox_CursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_CursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_CursoActionPerformed

    private void ComboBox_CursoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ComboBox_CursoAncestorAdded
        // TODO add your handling code here:
        try {
            CursoV4DAO dao = new CursoV4DAO();
            ArrayList<CursoV4> lista = dao.listarCursos();

            ComboBox_Curso.removeAllItems();

            for (CursoV4 c : lista) {
                ComboBox_Curso.addItem(c.getNome_curso());
            }
        } catch (SQLException ex) {
            ex.printStackTrace(); // Print the stack trace to see the details of the exception
            // Handle the exception as per your application's requirements
        }
    }//GEN-LAST:event_ComboBox_CursoAncestorAdded

    private void ComboBox_AlunoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ComboBox_AlunoAncestorAdded
        // TODO add your handling code here:
        try {
            AlunoV4DAO dao = new AlunoV4DAO();
            ArrayList<AlunoV4> lista = dao.listarRA();

            ComboBox_Aluno.removeAllItems();

            for (AlunoV4 c : lista) {
                ComboBox_Aluno.addItem(c.getNome_aluno());
            }
        } catch (SQLException ex) {
            ex.printStackTrace(); // Print the stack trace to see the details of the exception
            // Handle the exception as per your application's requirements
        }
    }//GEN-LAST:event_ComboBox_AlunoAncestorAdded

    private void ComboBox_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_AlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_AlunoActionPerformed

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        // TODO add your handling code here:
        FormEditor editar = new FormEditor();
        editar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_VoltarActionPerformed

    private void btn_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeletarActionPerformed
        // TODO add your handling code here:
        String idMatricula = JOptionPane.showInputDialog(this, "Insira o id da matrícula a ser deletado:");

        // Verifica se um valor foi inserido
        if (idMatricula != null && !idMatricula.trim().isEmpty()) {
            try {
                MatriculaV4DAO dao = new MatriculaV4DAO();
                int IDMatricula = Integer.parseInt(idMatricula.trim()); // Converte o id para inteiro
                dao.deletar(IDMatricula); // Assume que o método deletar no DAO aceita um id como inteiro
                JOptionPane.showMessageDialog(this, "Matrícula deletado com sucesso!");
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "id inválido. Insira um número válido.");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao deletar matrícula.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "id não inserido.");
        }
    }//GEN-LAST:event_btn_DeletarActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMatriculaV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMatriculaV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMatriculaV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMatriculaV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMatriculaV4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_Aluno;
    private javax.swing.JComboBox<String> ComboBox_Curso;
    private javax.swing.JLabel Label_Conclusao;
    private javax.swing.JLabel Label_Conclusao1;
    private javax.swing.JLabel Label_Conclusao2;
    private javax.swing.JLabel Label_Conclusao3;
    private javax.swing.JLabel Label_Efetivacao;
    private javax.swing.JLabel Label_Efetivacao1;
    private javax.swing.JToggleButton btn_Atualizar;
    private javax.swing.JToggleButton btn_Deletar;
    private javax.swing.JToggleButton btn_Inserir;
    private javax.swing.JToggleButton btn_Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_Data_Conclusão;
    private javax.swing.JTextField txt_Data_Efetivação;
    // End of variables declaration//GEN-END:variables
}
