/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import com.mycompany.db.ConnectionFactory;
import beans.MatriculaV4;
import dao.MatriculaV4DAO;


/**
 *
 * @author pedro
 */
public class FormsMatriculaV4 extends javax.swing.JFrame {

    /**
     * Creates new form FormsMatriculaV4
     */
    public FormsMatriculaV4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Frame = new javax.swing.JPanel();
        txt_MATRICULA = new javax.swing.JTextField();
        Label_Data_Conclsão = new javax.swing.JTextField();
        Label_Data_Efetivacao = new javax.swing.JTextField();
        btn_Atualizar = new javax.swing.JToggleButton();
        btn_Deletar = new javax.swing.JToggleButton();
        btn_Inserir = new javax.swing.JToggleButton();
        txt_Data_Efetivação = new javax.swing.JTextField();
        txt_Data_Conclusão = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main_Frame.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_MATRICULA.setEditable(false);
        txt_MATRICULA.setBackground(new java.awt.Color(230, 230, 230));
        txt_MATRICULA.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        txt_MATRICULA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_MATRICULA.setText("MATRÍCULA");
        txt_MATRICULA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_MATRICULA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MATRICULAActionPerformed(evt);
            }
        });

        Label_Data_Conclsão.setEditable(false);
        Label_Data_Conclsão.setBackground(new java.awt.Color(230, 230, 230));
        Label_Data_Conclsão.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_Data_Conclsão.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Label_Data_Conclsão.setText("Data de Conclusão");
        Label_Data_Conclsão.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Label_Data_Efetivacao.setEditable(false);
        Label_Data_Efetivacao.setBackground(new java.awt.Color(230, 230, 230));
        Label_Data_Efetivacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Label_Data_Efetivacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Label_Data_Efetivacao.setText("Data de Efetivação");
        Label_Data_Efetivacao.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_Atualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Atualizar.setText("ATUALIZAR");
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });

        btn_Deletar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Deletar.setText("DELETAR");
        btn_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeletarActionPerformed(evt);
            }
        });

        btn_Inserir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Inserir.setText("INSERIR");
        btn_Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InserirActionPerformed(evt);
            }
        });

        txt_Data_Efetivação.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Data_Efetivação.setText("YY--MM--DD");
        txt_Data_Efetivação.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Data_Efetivação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Data_EfetivaçãoActionPerformed(evt);
            }
        });

        txt_Data_Conclusão.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout Main_FrameLayout = new javax.swing.GroupLayout(Main_Frame);
        Main_Frame.setLayout(Main_FrameLayout);
        Main_FrameLayout.setHorizontalGroup(
            Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_FrameLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Main_FrameLayout.createSequentialGroup()
                        .addComponent(txt_Data_Efetivação, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Data_Conclusão))
                    .addGroup(Main_FrameLayout.createSequentialGroup()
                        .addComponent(Label_Data_Efetivacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label_Data_Conclsão, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Main_FrameLayout.createSequentialGroup()
                        .addComponent(btn_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_MATRICULA))
                .addGap(37, 37, 37))
        );
        Main_FrameLayout.setVerticalGroup(
            Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_FrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_MATRICULA, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Data_Conclsão, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Data_Efetivacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Data_Efetivação, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Data_Conclusão, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Main_FrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Main_Frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Main_Frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MATRICULAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MATRICULAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MATRICULAActionPerformed

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        // TODO add your handling code here:
        String dataEfetivacao = txt_Data_Efetivação.getText();
        String dataTermino = txt_Data_Conclusão.getText();

        MatriculaV4 matricula = new MatriculaV4();
        matricula.setData_efetivacao(dataEfetivacao);
        matricula.setData_termino(dataTermino);

        try {
            MatriculaV4DAO dao = new MatriculaV4DAO();
            dao.atualizar(matricula);
            JOptionPane.showMessageDialog(this, "Matrícula atualizado com sucesso!");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao atualizar Matrícula.");
        }
    }//GEN-LAST:event_btn_AtualizarActionPerformed

    private void btn_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeletarActionPerformed
        // TODO add your handling code here:
        String idMatricula = JOptionPane.showInputDialog(this, "Insira o ID da matricula a ser deletada:");

        
        if (idMatricula != null && !idMatricula.trim().isEmpty()) { 
        try {
            MatriculaV4DAO dao = new MatriculaV4DAO();
            int id_matricula = Integer.parseInt(idMatricula.trim()); // Converte o ID para inteiro
            dao.deletar(id_matricula); // Assume que o método deletar no DAO aceita um ID como inteiro
            JOptionPane.showMessageDialog(this, "Matrícula deletada com sucesso!");
        } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "ID inválido. Insira um número válido.");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao deletar matrícula.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "ID não inserido.");
        }
    }//GEN-LAST:event_btn_DeletarActionPerformed

    private void btn_InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InserirActionPerformed
        // TODO add your handling code here:
        String dataEfetivacao = txt_Data_Efetivação.getText();
        String dataTermino = txt_Data_Conclusão.getText();

        MatriculaV4 matricula = new MatriculaV4();
        matricula.setData_efetivacao(dataEfetivacao);
        matricula.setData_termino(dataTermino);

        try {
            MatriculaV4DAO dao = new MatriculaV4DAO();
            dao.inserir(matricula);
            JOptionPane.showMessageDialog(this, "Matrícula inserido com sucesso!");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao inserir matrícula.");
        }
    }//GEN-LAST:event_btn_InserirActionPerformed

    private void txt_Data_EfetivaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Data_EfetivaçãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Data_EfetivaçãoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormsMatriculaV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormsMatriculaV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormsMatriculaV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormsMatriculaV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormsMatriculaV4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Label_Data_Conclsão;
    private javax.swing.JTextField Label_Data_Efetivacao;
    private javax.swing.JPanel Main_Frame;
    private javax.swing.JToggleButton btn_Atualizar;
    private javax.swing.JToggleButton btn_Deletar;
    private javax.swing.JToggleButton btn_Inserir;
    private javax.swing.JTextField txt_Data_Conclusão;
    private javax.swing.JTextField txt_Data_Efetivação;
    private javax.swing.JTextField txt_MATRICULA;
    // End of variables declaration//GEN-END:variables
}
