/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import beans.AlunoV4;
import dao.AlunoV4DAO;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class FormNotas extends javax.swing.JFrame {

    /**
     * Creates new form FormNotas
     */
    public FormNotas() {
        initComponents();
       this.setSize(960, 600);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_buscar = new javax.swing.JButton();
        txt_RA = new javax.swing.JTextField();
        Label_RA = new javax.swing.JLabel();
        txt_A1 = new javax.swing.JTextField();
        txt_A2 = new javax.swing.JTextField();
        txt_A3 = new javax.swing.JTextField();
        Label_A1 = new javax.swing.JLabel();
        Label_A2 = new javax.swing.JLabel();
        Label_A3 = new javax.swing.JLabel();
        btn_Voltar = new javax.swing.JButton();
        Presenças = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_buscar.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(204, 204, 204));
        btn_buscar.setText("BUSCAR");
        btn_buscar.setBorder(null);
        btn_buscar.setContentAreaFilled(false);
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar);
        btn_buscar.setBounds(207, 495, 130, 35);

        txt_RA.setBackground(new java.awt.Color(3, 16, 50));
        txt_RA.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        txt_RA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_RA.setBorder(null);
        getContentPane().add(txt_RA);
        txt_RA.setBounds(170, 210, 160, 33);

        Label_RA.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_RA.setForeground(new java.awt.Color(204, 204, 204));
        Label_RA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_RA.setText("RA:");
        getContentPane().add(Label_RA);
        Label_RA.setBounds(87, 190, 30, 30);

        txt_A1.setEditable(false);
        txt_A1.setBackground(new java.awt.Color(3, 16, 50));
        txt_A1.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        txt_A1.setForeground(new java.awt.Color(204, 204, 204));
        txt_A1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_A1.setBorder(null);
        txt_A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_A1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_A1);
        txt_A1.setBounds(170, 284, 160, 33);

        txt_A2.setEditable(false);
        txt_A2.setBackground(new java.awt.Color(3, 16, 50));
        txt_A2.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        txt_A2.setForeground(new java.awt.Color(204, 204, 204));
        txt_A2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_A2.setBorder(null);
        txt_A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_A2ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_A2);
        txt_A2.setBounds(170, 359, 160, 33);

        txt_A3.setEditable(false);
        txt_A3.setBackground(new java.awt.Color(3, 16, 50));
        txt_A3.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        txt_A3.setForeground(new java.awt.Color(204, 204, 204));
        txt_A3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_A3.setAlignmentY(0.9F);
        txt_A3.setBorder(null);
        txt_A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_A3ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_A3);
        txt_A3.setBounds(170, 431, 160, 33);

        Label_A1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_A1.setForeground(new java.awt.Color(204, 204, 204));
        Label_A1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_A1.setText("A1:");
        getContentPane().add(Label_A1);
        Label_A1.setBounds(86, 268, 30, 20);

        Label_A2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_A2.setForeground(new java.awt.Color(204, 204, 204));
        Label_A2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_A2.setText("A2:");
        getContentPane().add(Label_A2);
        Label_A2.setBounds(86, 338, 30, 30);

        Label_A3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        Label_A3.setForeground(new java.awt.Color(204, 204, 204));
        Label_A3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_A3.setText("A3:");
        getContentPane().add(Label_A3);
        Label_A3.setBounds(86, 411, 30, 30);

        btn_Voltar.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_Voltar.setForeground(new java.awt.Color(204, 204, 204));
        btn_Voltar.setText("< VOLTAR");
        btn_Voltar.setBorder(null);
        btn_Voltar.setContentAreaFilled(false);
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Voltar);
        btn_Voltar.setBounds(43, 495, 130, 35);

        Presenças.setEditable(false);
        Presenças.setBackground(new java.awt.Color(23, 27, 80));
        Presenças.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        Presenças.setForeground(new java.awt.Color(140, 82, 255));
        Presenças.setText("Notas");
        Presenças.setBorder(null);
        Presenças.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresençasActionPerformed(evt);
            }
        });
        getContentPane().add(Presenças);
        Presenças.setBounds(140, 110, 110, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pedro\\Desktop\\DesignNovo\\Notas.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 950, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_A1ActionPerformed
        // TODO add your handling code here:      
    }//GEN-LAST:event_txt_A1ActionPerformed

    private void txt_A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_A2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_A2ActionPerformed

    private void txt_A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_A3ActionPerformed

    private void buscarNotas(int RA) {
        try {
            AlunoV4DAO dao = new AlunoV4DAO();
            AlunoV4 aluno = dao.buscarNotasPorRA(RA);

            if (aluno != null) {
                txt_A1.setText(aluno.getNota_A1());
                txt_A2.setText(aluno.getNota_A2());
                txt_A3.setText(aluno.getNota_A3());
            } else {
                JOptionPane.showMessageDialog(this, "Notas não encontradas para o RA: " + RA);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar notas: " + ex.getMessage());
        }
    }


    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        // TODO add your handling code here:
        FormChecarAluno checar = new FormChecarAluno();
        checar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_VoltarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        String raText = txt_RA.getText().trim();
        if (!raText.isEmpty()) {
            try {
                int ra = Integer.parseInt(raText);
                buscarNotas(ra);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "RA deve ser um número válido.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, insira um RA.");
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void PresençasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresençasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresençasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNotas().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_A1;
    private javax.swing.JLabel Label_A2;
    private javax.swing.JLabel Label_A3;
    private javax.swing.JLabel Label_RA;
    private javax.swing.JTextField Presenças;
    private javax.swing.JButton btn_Voltar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_A1;
    private javax.swing.JTextField txt_A2;
    private javax.swing.JTextField txt_A3;
    private javax.swing.JTextField txt_RA;
    // End of variables declaration//GEN-END:variables
}
