/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import beans.CursoV4;
import dao.CursoV4DAO;
import beans.AlunoV4;
import dao.AlunoV4DAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author pedro
 */
public class FormAlunoV4 extends javax.swing.JFrame {

    /**
     * Creates new form AlunoV4
     */
    public FormAlunoV4() {
        initComponents();
        this.setSize(500, 670);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_Nome = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_Telefone = new javax.swing.JTextField();
        txt_Endereco = new javax.swing.JTextField();
        txt_Nome_responsavel = new javax.swing.JTextField();
        txt_Data_nascimento = new javax.swing.JTextField();
        Label_Nome = new javax.swing.JLabel();
        Label_Email = new javax.swing.JLabel();
        Label_Telefone = new javax.swing.JLabel();
        Label_Endereco = new javax.swing.JLabel();
        Label_DataNasc = new javax.swing.JLabel();
        Label_NomeResp = new javax.swing.JLabel();
        Label_Curso = new javax.swing.JLabel();
        ComboBox_Curso = new javax.swing.JComboBox<>();
        Label_Senha = new javax.swing.JLabel();
        txt_Senha = new javax.swing.JTextField();
        btn_Atualizar = new javax.swing.JToggleButton();
        btn_Inserir = new javax.swing.JToggleButton();
        btn_Voltar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Aluno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Schoolbook", 1, 24))); // NOI18N

        txt_Nome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_Nome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Nome.setMinimumSize(new java.awt.Dimension(30, 40));
        txt_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NomeActionPerformed(evt);
            }
        });

        txt_email.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_email.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_email.setMinimumSize(new java.awt.Dimension(30, 40));
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        txt_Telefone.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_Telefone.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Telefone.setMinimumSize(new java.awt.Dimension(30, 40));
        txt_Telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TelefoneActionPerformed(evt);
            }
        });

        txt_Endereco.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_Endereco.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Endereco.setMinimumSize(new java.awt.Dimension(30, 40));
        txt_Endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EnderecoActionPerformed(evt);
            }
        });

        txt_Nome_responsavel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_Nome_responsavel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Nome_responsavel.setMinimumSize(new java.awt.Dimension(30, 40));
        txt_Nome_responsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nome_responsavelActionPerformed(evt);
            }
        });

        txt_Data_nascimento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_Data_nascimento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Data_nascimento.setMinimumSize(new java.awt.Dimension(30, 40));
        txt_Data_nascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Data_nascimentoActionPerformed(evt);
            }
        });

        Label_Nome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Nome.setText("Nome:");
        Label_Nome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Label_Email.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Email.setText("Email:");
        Label_Email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Label_Telefone.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Telefone.setText("Telefone:");
        Label_Telefone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Label_Endereco.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Endereco.setText("Endereço");
        Label_Endereco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Label_DataNasc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_DataNasc.setText("Data de Nascimento:");
        Label_DataNasc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Label_NomeResp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_NomeResp.setText("Nome do Responsável:");
        Label_NomeResp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Label_Curso.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Curso.setText("Curso:");
        Label_Curso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        ComboBox_Curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_Curso.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ComboBox_CursoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ComboBox_Curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_CursoActionPerformed(evt);
            }
        });

        Label_Senha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Label_Senha.setText("Senha:");
        Label_Senha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        txt_Senha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_Senha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txt_Senha.setMinimumSize(new java.awt.Dimension(30, 40));
        txt_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SenhaActionPerformed(evt);
            }
        });

        btn_Atualizar.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_Atualizar.setText("ATUALIZAR");
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });

        btn_Inserir.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_Inserir.setText("INSERIR");
        btn_Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InserirActionPerformed(evt);
            }
        });

        btn_Voltar.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_Voltar.setText("< Voltar");
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Label_NomeResp, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_Curso, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboBox_Curso, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Nome_responsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Label_DataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Data_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btn_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Data_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_DataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Nome_responsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_NomeResp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Curso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_Curso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomeActionPerformed

    private void txt_TelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TelefoneActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_EnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EnderecoActionPerformed

    private void txt_Nome_responsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nome_responsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nome_responsavelActionPerformed

    private void txt_Data_nascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Data_nascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Data_nascimentoActionPerformed

    private void btn_InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InserirActionPerformed
        // TODO add your handling code here:
        String nomeAluno = txt_Nome.getText();
        String email = txt_email.getText();
        String endereco = txt_Endereco.getText();
        String telefone = txt_Telefone.getText();
        String nomeResp = txt_Nome_responsavel.getText();
        String dataNascimento = txt_Data_nascimento.getText();
        String senhaAluno = txt_Senha.getText();
        // Obtendo o ID do curso selecionado na Combo Box
        int idCursoSelecionado = ComboBox_Curso.getSelectedIndex() + 1;

        AlunoV4 aluno = new AlunoV4();
        aluno.setNome_aluno(nomeAluno);
        aluno.setEmail_aluno(email);
        aluno.setNome_responsavel_aluno(nomeResp);
        aluno.setData_nascimento_aluno(dataNascimento);
        aluno.setTelefone_aluno(telefone);
        aluno.setEndereco_aluno(endereco);
        aluno.setSenha_aluno(senhaAluno);

        try {
            AlunoV4DAO dao = new AlunoV4DAO();
            dao.inserir(aluno, idCursoSelecionado);
            JOptionPane.showMessageDialog(this, "Aluno inserido com sucesso!");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao inserir Aluno.");
        }
    }//GEN-LAST:event_btn_InserirActionPerformed

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        // TODO add your handling code here:
        String raStr = JOptionPane.showInputDialog(this, "Informe o RA do aluno a ser atualizado:");
        if (raStr == null || raStr.isEmpty()) {
            return; // Se o usuário cancelar ou não fornecer o RA, interromper a operação
        }

        try {
            int ra = Integer.parseInt(raStr);
            AlunoV4DAO dao = new AlunoV4DAO();
            AlunoV4 aluno = dao.buscarPorRA(ra);

            if (aluno == null) {
                JOptionPane.showMessageDialog(this, "Aluno não encontrado.");
                return;
            }

            // Solicitar novas informações
            String nomeAluno = JOptionPane.showInputDialog(this, "Nome do aluno:", aluno.getNome_aluno());
            String email = JOptionPane.showInputDialog(this, "Email do aluno:", aluno.getEmail_aluno());
            String telefone = JOptionPane.showInputDialog(this, "Telefone do aluno:", aluno.getTelefone_aluno());
            String dataNascimento = JOptionPane.showInputDialog(this, "Data de Nascimento do aluno:", aluno.getData_nascimento_aluno());
            String endereco = JOptionPane.showInputDialog(this, "Endereço do aluno:", aluno.getEndereco_aluno());
            String nomeResp = JOptionPane.showInputDialog(this, "Nome do responsável:", aluno.getNome_responsavel_aluno());
            String senhaAluno = JOptionPane.showInputDialog(this, "Senha:", aluno.getSenha_aluno());

            // Obtendo o ID do curso selecionado na Combo Box
            int idCursoSelecionado = ComboBox_Curso.getSelectedIndex() + 1;

            // Atualizar o objeto aluno com novas informações
            aluno.setNome_aluno(nomeAluno);
            aluno.setEmail_aluno(email);
            aluno.setTelefone_aluno(telefone);
            aluno.setData_nascimento_aluno(dataNascimento);
            aluno.setEndereco_aluno(endereco);
            aluno.setNome_responsavel_aluno(nomeResp);
            aluno.setSenha_aluno(senhaAluno);

            // Atualizar no banco de dados
            dao.atualizar(aluno, idCursoSelecionado);
            JOptionPane.showMessageDialog(this, "Aluno atualizado com sucesso!");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "RA inválido.");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao atualizar Aluno.");
        }
    }//GEN-LAST:event_btn_AtualizarActionPerformed

    private void ComboBox_CursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_CursoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ComboBox_CursoActionPerformed

    private void ComboBox_CursoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ComboBox_CursoAncestorAdded
        // TODO add your handling code here:

        try {
            CursoV4DAO dao = new CursoV4DAO();
            ArrayList<CursoV4> lista = dao.listarCursos();

            ComboBox_Curso.removeAllItems();

            for (CursoV4 c : lista) {
                ComboBox_Curso.addItem(c.getNome_curso());
            }
        } catch (SQLException ex) {
            ex.printStackTrace(); // Print the stack trace to see the details of the exception
            // Handle the exception as per your application's requirements
        }

    }//GEN-LAST:event_ComboBox_CursoAncestorAdded

    private void txt_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SenhaActionPerformed

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        // TODO add your handling code here:
        FormRegistrar registro = new FormRegistrar();
        registro.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btn_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAlunoV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAlunoV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAlunoV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAlunoV4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAlunoV4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_Curso;
    private javax.swing.JLabel Label_Curso;
    private javax.swing.JLabel Label_DataNasc;
    private javax.swing.JLabel Label_Email;
    private javax.swing.JLabel Label_Endereco;
    private javax.swing.JLabel Label_Nome;
    private javax.swing.JLabel Label_NomeResp;
    private javax.swing.JLabel Label_Senha;
    private javax.swing.JLabel Label_Telefone;
    private javax.swing.JToggleButton btn_Atualizar;
    private javax.swing.JToggleButton btn_Inserir;
    private javax.swing.JToggleButton btn_Voltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_Data_nascimento;
    private javax.swing.JTextField txt_Endereco;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_Nome_responsavel;
    private javax.swing.JTextField txt_Senha;
    private javax.swing.JTextField txt_Telefone;
    private javax.swing.JTextField txt_email;
    // End of variables declaration//GEN-END:variables
}
