/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import dao.AlunoV4DAO;
import dao.ProfessorV4DAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class FormEditor extends javax.swing.JFrame {

    /**
     * Creates new form FormEditor
     */
    public FormEditor() {
        initComponents();
         this.setSize(960, 600);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Mensalidade = new javax.swing.JButton();
        btn_Cursos = new javax.swing.JButton();
        Matricula = new javax.swing.JButton();
        btn_Menu = new javax.swing.JButton();
        btn_deletarA = new javax.swing.JButton();
        btn_deletarP = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_Mensalidade.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_Mensalidade.setForeground(new java.awt.Color(204, 204, 204));
        btn_Mensalidade.setText("MENSALIDADE");
        btn_Mensalidade.setBorder(null);
        btn_Mensalidade.setContentAreaFilled(false);
        btn_Mensalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MensalidadeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Mensalidade);
        btn_Mensalidade.setBounds(110, 184, 182, 30);

        btn_Cursos.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_Cursos.setForeground(new java.awt.Color(204, 204, 204));
        btn_Cursos.setText("CURSOS");
        btn_Cursos.setBorder(null);
        btn_Cursos.setContentAreaFilled(false);
        btn_Cursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CursosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cursos);
        btn_Cursos.setBounds(110, 244, 180, 30);

        Matricula.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        Matricula.setForeground(new java.awt.Color(204, 204, 204));
        Matricula.setText("MATRÍCULA");
        Matricula.setBorder(null);
        Matricula.setContentAreaFilled(false);
        Matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculaActionPerformed(evt);
            }
        });
        getContentPane().add(Matricula);
        Matricula.setBounds(110, 305, 182, 30);

        btn_Menu.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        btn_Menu.setForeground(new java.awt.Color(204, 204, 204));
        btn_Menu.setText("Menu");
        btn_Menu.setBorder(null);
        btn_Menu.setContentAreaFilled(false);
        btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Menu);
        btn_Menu.setBounds(100, 488, 190, 30);

        btn_deletarA.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_deletarA.setForeground(new java.awt.Color(204, 204, 204));
        btn_deletarA.setText("DELETAR Aluno");
        btn_deletarA.setBorder(null);
        btn_deletarA.setContentAreaFilled(false);
        btn_deletarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletarAActionPerformed(evt);
            }
        });
        getContentPane().add(btn_deletarA);
        btn_deletarA.setBounds(110, 425, 180, 33);

        btn_deletarP.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btn_deletarP.setForeground(new java.awt.Color(204, 204, 204));
        btn_deletarP.setText("DELETAR Prof.");
        btn_deletarP.setBorder(null);
        btn_deletarP.setContentAreaFilled(false);
        btn_deletarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletarPActionPerformed(evt);
            }
        });
        getContentPane().add(btn_deletarP);
        btn_deletarP.setBounds(110, 367, 180, 33);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(23, 27, 80));
        jTextField1.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(140, 82, 255));
        jTextField1.setText("Acesso Restrito");
        jTextField1.setToolTipText("");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(60, 60, 289, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\pedro\\Desktop\\DesignNovo\\Editor.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CursosActionPerformed
        // TODO add your handling code here:
        FormCursoV4 CursoV4 = new FormCursoV4();
        CursoV4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CursosActionPerformed

    private void btn_MensalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MensalidadeActionPerformed
        // TODO add your handling code here:
        FormMensalidadeV4 MensalidadeV4 = new FormMensalidadeV4();
        MensalidadeV4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_MensalidadeActionPerformed

    private void btn_deletarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletarAActionPerformed
        // TODO add your handling code here:
        String raAluno = JOptionPane.showInputDialog(this, "Insira o RA do aluno a ser deletado:");

        // Verifica se um valor foi inserido
        if (raAluno != null && !raAluno.trim().isEmpty()) {
            try {
                AlunoV4DAO dao = new AlunoV4DAO();
                int ra = Integer.parseInt(raAluno.trim()); // Converte o RA para inteiro
                dao.deletar(ra); // Assume que o método deletar no DAO aceita um RA como inteiro
                JOptionPane.showMessageDialog(this, "Aluno deletado com sucesso!");
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "RA inválido. Insira um número válido.");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao deletar aluno.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "RA não inserido.");
        }
    }//GEN-LAST:event_btn_deletarAActionPerformed

    private void btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuActionPerformed
        // TODO add your handling code here:
        FormTelaMenu menu = new FormTelaMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_MenuActionPerformed

    private void MatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculaActionPerformed
        // TODO add your handling code here:
        FormMatriculaV4 matricula = new FormMatriculaV4();
        matricula.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MatriculaActionPerformed

    private void btn_deletarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletarPActionPerformed
        // TODO add your handling code here:
        String idProfessor = JOptionPane.showInputDialog(this, "Insira o ID do professor a ser deletado:");

        // Verifica se um valor foi inserido
        if (idProfessor != null && !idProfessor.trim().isEmpty()) {
            try {
                ProfessorV4DAO dao = new ProfessorV4DAO();
                int ID = Integer.parseInt(idProfessor.trim()); // Converte o ID para inteiro
                dao.deletar(ID); // Assume que o método deletar no DAO aceita um ID como inteiro
                JOptionPane.showMessageDialog(this, "Professor deletado com sucesso!");
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "ID inválido. Insira um número válido.");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Erro ao deletar professor.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "ID não inserido.");
        }
    }//GEN-LAST:event_btn_deletarPActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Matricula;
    private javax.swing.JButton btn_Cursos;
    private javax.swing.JButton btn_Mensalidade;
    private javax.swing.JButton btn_Menu;
    private javax.swing.JButton btn_deletarA;
    private javax.swing.JButton btn_deletarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
